#!/bin/bash

function addToPath
{
  local P=$1; shift

  for DIR in "$@"; do
    [ -e $DIR ] && [[ :"${!P}": != *:"$DIR":* ]] && eval "$P=$DIR${!P:+:${!P}}"
  done
}

export HIERS=$HOME/hiers

for F in $HIERS/[!.]*; do
  addToPath PATH            $F/bin
  addToPath LD_LIBRARY_PATH $F/{,usr/}lib{,64}
  addToPath PKG_CONFIG_PATH $F/{,usr/}lib{,64}/pkgconfig
  addToPath MANPATH         $F/{,share/}man
  addToPath PYTHONPATH      $F/lib/python2.7/site-packages
done

export PATH LD_LIBRARY_PATH PYTHONPATH MANPATH

set -o vi
export EDITOR=vim

export PROMPT_COMMAND=__prompt_command

function __prompt_command() {
  local RC=$?
  if [ $RC != 0 ]; then
    local STATUS='\[\e[0;31m\]'[$RC]'\[\e[0m\] '
  fi

  PS1="\s-\v$STATUS\$ "
}

export TERM=xterm-256color

if [ -r $HOME/.bashrc.local ]; then
  . $HOME/.bashrc.local
fi

